'use client';

import React, { useState } from 'react';
import {
  Brain,
  Sparkles,
  Bot,
  UserCheck,
  AlertTriangle,
  CheckCircle2,
  HelpCircle,
  Copy,
  RefreshCw,
  Zap,
  Gauge,
  Activity,
  Layers,
  Search,
  ExternalLink,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Flame,
  FileWarning,
  Lock,
  DollarSign
} from 'lucide-react';
import { Card } from '../ui/Card';
import { useToast } from '../ui/Toast';

export function AIContentDetectorCard({
  detection,
  onRerun,
  isLoading = false,
  rawText = '',
  subject = ''
}) {
  const { toast } = useToast();
  const [selectedSentenceIndex, setSelectedSentenceIndex] = useState(null);
  const [filterLevel, setFilterLevel] = useState('ALL'); // 'ALL' | 'AI_ONLY' | 'DECEPTIVE_ONLY' | 'HUMAN_ONLY'

  if (!detection) return null;

  const {
    aiProbability = 50,
    authorshipVerdict = 'MIXED_OR_PARAPHRASED',
    verdict = authorshipVerdict,
    threatScore = 0,
    isFake = false,
    isHarmful = false,
    isLegitimate = true,
    threatVerdict = 'LEGITIMATE_SAFE',
    threatCategory = 'BENIGN_LEGITIMATE',
    quadMatrixVerdict = 'AI_GENERATED_LEGITIMATE',
    threatIndicators = [],
    confidence = 85,
    engine = 'AEGIS Forensic Engine',
    model = 'gemini-3.6-flash',
    isOfflineFallback = false,
    summary = '',
    metrics = {},
    hallmarks = [],
    linguisticIndicators = [],
    perSentenceAnalysis = [],
    suggestedAnalystAction = ''
  } = detection;

  const isHighAi = aiProbability >= 70;
  const isModerateAi = aiProbability >= 45 && aiProbability < 70;
  const isHuman = aiProbability < 45;

  const isCriticalThreat = threatScore >= 70 || isHarmful;
  const isModerateThreat = threatScore >= 35 && threatScore < 70;
  const isSafeThreat = threatScore < 35 && !isHarmful;

  const copyReport = () => {
    const reportText = `[AEGIS DUAL-MATRIX FORENSIC REPORT]
Quad-Matrix Verdict: ${quadMatrixVerdict}
Authorship Origin: ${authorshipVerdict} (AI Likelihood: ${aiProbability}%)
Threat Status: ${threatVerdict} (Threat Score: ${threatScore}%)
Classification: ${isFake ? 'FAKE / DECEPTIVE' : 'AUTHENTIC'} | ${isHarmful ? 'HARMFUL ATTACK' : 'BENIGN / SAFE'}
Primary Category: ${threatCategory}
Confidence: ${confidence}%
Model/Engine: ${model} (${engine})

FORENSIC METRICS:
- Burstiness CV: ${metrics?.burstiness?.cv || 'N/A'}
- Token Predictability: ${metrics?.perplexity?.predictabilityScore || 'N/A'}/100
- LLM Hallmarks Detected: ${hallmarks.length}
- Threat Indicators Detected: ${threatIndicators.length}

EXECUTIVE SUMMARY:
${summary}

RECOMMENDED ANALYST ACTION:
${suggestedAnalystAction}`;

    navigator.clipboard.writeText(reportText);
    toast('Report Copied', 'Dual-matrix synthetic & threat analysis copied to clipboard', 'success');
  };

  const selectedSentence =
    selectedSentenceIndex !== null
      ? perSentenceAnalysis.find((s) => s.index === selectedSentenceIndex)
      : null;

  const filteredSentences = perSentenceAnalysis.filter((s) => {
    if (filterLevel === 'AI_ONLY') return s.aiProbability >= 60;
    if (filterLevel === 'DECEPTIVE_ONLY') return Boolean(s.isDeceptive);
    if (filterLevel === 'HUMAN_ONLY') return s.aiProbability < 50;
    return true;
  });

  // Quad-Matrix presentation helpers
  const getQuadMatrixBadge = () => {
    switch (quadMatrixVerdict) {
      case 'AI_GENERATED_HARMFUL':
        return {
          icon: <Flame className="w-4 h-4" />,
          title: 'AI-GENERATED & HARMFUL (AUTOMATED PHISHING ATTACK)',
          color: 'bg-red-500/20 text-red-400 border-red-500/40 shadow-glowRed',
          desc: 'Synthetic text generated by an LLM to conduct malicious credential harvesting, deception, or financial fraud.'
        };
      case 'AI_GENERATED_LEGITIMATE':
        return {
          icon: <Sparkles className="w-4 h-4" />,
          title: 'AI-GENERATED & LEGITIMATE (AI-ASSISTED BENIGN)',
          color: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/40 shadow-glowCyan',
          desc: 'Generated with AI assistance (e.g. marketing draft, corporate recap, newsletter) with zero fraudulent or harmful intent.'
        };
      case 'HUMAN_AUTHORED_HARMFUL':
        return {
          icon: <ShieldAlert className="w-4 h-4" />,
          title: 'HUMAN-AUTHORED & HARMFUL (MANUAL FRAUD / BEC)',
          color: 'bg-orange-500/20 text-orange-400 border-orange-500/40 shadow-glowAmber',
          desc: 'Crafted manually by a human attacker for targeted spear phishing, CEO wire fraud, or social engineering extortion.'
        };
      case 'HUMAN_AUTHORED_LEGITIMATE':
        return {
          icon: <ShieldCheck className="w-4 h-4" />,
          title: 'HUMAN-AUTHORED & LEGITIMATE (SAFE ROUTINE)',
          color: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40 shadow-glowGreen',
          desc: 'Authentic human-written email with organic linguistic cadence and safe, non-malicious content.'
        };
      default:
        return {
          icon: <AlertTriangle className="w-4 h-4" />,
          title: 'SUSPICIOUS ANOMALY (ELEVATED SCRUTINY REQUIRED)',
          color: 'bg-amber-500/20 text-amber-400 border-amber-500/40',
          desc: 'Displays conflicting or borderline indicators requiring human investigator verification.'
        };
    }
  };

  const quadBadge = getQuadMatrixBadge();

  return (
    <div className="space-y-6">
      {/* 1. Quad-Matrix Master Classification Banner */}
      <div className={`p-4 rounded-2xl border flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 ${quadBadge.color}`}>
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-darkBg/60 border border-current shrink-0">
            {quadBadge.icon}
          </div>
          <div>
            <div className="text-[10px] font-mono tracking-widest uppercase opacity-80">
              Forensic Quad-Matrix Classification
            </div>
            <h4 className="text-sm font-extrabold font-mono tracking-tight">
              {quadBadge.title}
            </h4>
            <p className="text-xs opacity-90 mt-0.5 max-w-2xl font-sans">
              {quadBadge.desc}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <span className="text-[11px] font-mono px-3 py-1 rounded-lg bg-darkBg/60 border border-current">
            Category: <strong className="text-white">{threatCategory.replace(/_/g, ' ')}</strong>
          </span>
        </div>
      </div>

      {/* 2. Header Overview & Dual Gauge Display */}
      <Card className="p-6 border border-white/10 relative overflow-hidden bg-gradient-to-br from-surface to-surfaceSecondary">
        <div
          className={`absolute -top-24 -right-24 w-60 h-60 rounded-full blur-3xl opacity-20 pointer-events-none ${
            isCriticalThreat ? 'bg-red-500' : isModerateThreat ? 'bg-amber-500' : 'bg-emerald-500'
          }`}
        />

        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-6 pb-6 border-b border-white/10">
          <div className="space-y-2.5 max-w-xl">
            {/* Status Pills */}
            <div className="flex flex-wrap items-center gap-2">
              {/* Authorship Badge */}
              <span
                className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold tracking-wide uppercase border ${
                  isHighAi
                    ? 'bg-purpleAccent/20 text-purpleAccent border-purpleAccent/40'
                    : isModerateAi
                    ? 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40'
                    : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                }`}
              >
                {isHighAi ? <Bot className="w-3 h-3" /> : <UserCheck className="w-3 h-3" />}
                {authorshipVerdict.replace(/_/g, ' ')}
              </span>

              {/* Deception / Fake Badge */}
              <span
                className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold tracking-wide uppercase border ${
                  isFake
                    ? 'bg-red-500/20 text-red-400 border-red-500/40'
                    : 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40'
                }`}
              >
                {isFake ? <ShieldX className="w-3 h-3" /> : <ShieldCheck className="w-3 h-3" />}
                {isFake ? 'FAKE / DECEPTIVE' : 'AUTHENTIC SENDER'}
              </span>

              {/* Harm / Threat Badge */}
              <span
                className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold tracking-wide uppercase border ${
                  isHarmful
                    ? 'bg-red-600/20 text-red-300 border-red-500/40'
                    : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                }`}
              >
                {isHarmful ? <Flame className="w-3 h-3" /> : <CheckCircle2 className="w-3 h-3" />}
                {isHarmful ? 'HARMFUL THREAT' : 'BENIGN / SAFE'}
              </span>

              <span className="text-[11px] font-mono px-2 py-0.5 rounded-md bg-white/5 border border-white/10 text-textSecondary">
                Model: {model}
              </span>

              {isOfflineFallback && (
                <span className="text-[11px] font-mono px-2 py-0.5 rounded-md bg-cyanAccent/20 text-cyanAccent border border-cyanAccent/30">
                  ⚡ Deterministic Baseline
                </span>
              )}
            </div>

            <h3 className="text-xl font-bold font-heading text-textPrimary tracking-tight">
              {isCriticalThreat
                ? `Deceptive & Malicious Intent Detected (${threatCategory.replace(/_/g, ' ')})`
                : isModerateThreat
                ? 'Suspicious Elements Detected — Elevated Caution'
                : 'Clean & Safe Communication — No Threat Patterns'}
            </h3>

            <p className="text-xs text-textSecondary leading-relaxed">
              {summary}
            </p>
          </div>

          {/* Dual Score Gauges (Authorship + Threat) */}
          <div className="flex flex-wrap items-center gap-4 bg-darkBg/70 p-4 rounded-2xl border border-white/10 shrink-0">
            {/* Gauge 1: AI Probability */}
            <div className="text-center px-2">
              <div className="text-[10px] font-mono uppercase tracking-wider text-textSecondary mb-1 flex items-center justify-center gap-1">
                <Bot className="w-3 h-3 text-purpleAccent" /> AI Origin
              </div>
              <div
                className={`text-3xl font-extrabold font-mono tracking-tighter ${
                  isHighAi ? 'text-purpleAccent' : isModerateAi ? 'text-cyan-400' : 'text-emerald-400'
                }`}
              >
                {aiProbability}%
              </div>
              <div className="text-[9px] font-mono text-textSecondary mt-0.5">
                {isHighAi ? 'Synthetic' : isModerateAi ? 'Assisted' : 'Organic'}
              </div>
            </div>

            <div className="h-12 w-[1px] bg-white/10" />

            {/* Gauge 2: Threat & Harm Score */}
            <div className="text-center px-2">
              <div className="text-[10px] font-mono uppercase tracking-wider text-textSecondary mb-1 flex items-center justify-center gap-1">
                <ShieldAlert className="w-3 h-3 text-red-400" /> Threat Score
              </div>
              <div
                className={`text-3xl font-extrabold font-mono tracking-tighter ${
                  isCriticalThreat ? 'text-red-400' : isModerateThreat ? 'text-amber-400' : 'text-emerald-400'
                }`}
              >
                {threatScore}%
              </div>
              <div className="text-[9px] font-mono text-textSecondary mt-0.5">
                {isCriticalThreat ? 'Harmful' : isModerateThreat ? 'Suspicious' : 'Safe'}
              </div>
            </div>

            <div className="h-12 w-[1px] bg-white/10" />

            {/* Action Buttons */}
            <div className="flex flex-col gap-2">
              <button
                onClick={copyReport}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-surfaceSecondary hover:bg-white/10 border border-borderSubtle text-[11px] font-mono text-textPrimary transition-all"
              >
                <Copy className="w-3 h-3 text-purpleAccent" /> Copy Report
              </button>

              {onRerun && (
                <button
                  onClick={() => onRerun(false)}
                  disabled={isLoading}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-purpleAccent/20 hover:bg-purpleAccent/30 border border-purpleAccent/30 text-[11px] font-mono text-purpleAccent transition-all disabled:opacity-50"
                >
                  <RefreshCw className={`w-3 h-3 ${isLoading ? 'animate-spin' : ''}`} /> Rescan Dual-Matrix
                </button>
              )}
            </div>
          </div>
        </div>

        {/* 3. Forensic Multi-Metric Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-6">
          {/* Metric 1: Threat Severity */}
          <div className="p-4 rounded-xl bg-surfaceSecondary/70 border border-borderSubtle space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-mono text-textSecondary">
              <span className="flex items-center gap-1.5">
                <ShieldAlert className="w-3.5 h-3.5 text-red-400" /> Threat & Harm
              </span>
              <span className={`font-bold ${isCriticalThreat ? 'text-red-400' : 'text-emerald-400'}`}>
                {threatScore}/100
              </span>
            </div>
            <div className="w-full bg-darkBg/80 h-2 rounded-full overflow-hidden border border-white/5">
              <div
                className={`h-full transition-all duration-500 ${
                  threatScore >= 70 ? 'bg-red-500' : threatScore >= 35 ? 'bg-amber-500' : 'bg-emerald-500'
                }`}
                style={{ width: `${threatScore}%` }}
              />
            </div>
            <div className="text-[10px] text-textSecondary leading-tight">
              {isHarmful ? 'Harmful attack cues detected' : 'Zero malicious attack vectors'}
            </div>
          </div>

          {/* Metric 2: Burstiness */}
          <div className="p-4 rounded-xl bg-surfaceSecondary/70 border border-borderSubtle space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-mono text-textSecondary">
              <span className="flex items-center gap-1.5">
                <Activity className="w-3.5 h-3.5 text-primaryBlue" /> Burstiness
              </span>
              <span className="font-bold text-textPrimary">CV: {metrics.burstiness?.cv ?? '0.45'}</span>
            </div>
            <div className="w-full bg-darkBg/80 h-2 rounded-full overflow-hidden border border-white/5">
              <div
                className={`h-full transition-all duration-500 ${
                  (metrics.burstiness?.cv ?? 0.5) < 0.35
                    ? 'bg-purpleAccent'
                    : (metrics.burstiness?.cv ?? 0.5) < 0.6
                    ? 'bg-cyan-500'
                    : 'bg-emerald-500'
                }`}
                style={{ width: `${Math.min(100, ((metrics.burstiness?.cv ?? 0.5) / 1.0) * 100)}%` }}
              />
            </div>
            <div className="text-[10px] text-textSecondary leading-tight">
              {metrics.burstiness?.interpretation || 'Measures sentence length variation'}
            </div>
          </div>

          {/* Metric 3: Predictability */}
          <div className="p-4 rounded-xl bg-surfaceSecondary/70 border border-borderSubtle space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-mono text-textSecondary">
              <span className="flex items-center gap-1.5">
                <Gauge className="w-3.5 h-3.5 text-cyanAccent" /> Predictability
              </span>
              <span className="font-bold text-textPrimary">
                {metrics.perplexity?.predictabilityScore ?? 50}%
              </span>
            </div>
            <div className="w-full bg-darkBg/80 h-2 rounded-full overflow-hidden border border-white/5">
              <div
                className={`h-full transition-all duration-500 ${
                  (metrics.perplexity?.predictabilityScore ?? 50) > 70
                    ? 'bg-purpleAccent'
                    : (metrics.perplexity?.predictabilityScore ?? 50) > 45
                    ? 'bg-cyan-500'
                    : 'bg-emerald-500'
                }`}
                style={{ width: `${metrics.perplexity?.predictabilityScore ?? 50}%` }}
              />
            </div>
            <div className="text-[10px] text-textSecondary leading-tight">
              {metrics.perplexity?.rating || 'Measures vocabulary transition predictability'}
            </div>
          </div>

          {/* Metric 4: Hallmarks & Threat Flags Count */}
          <div className="p-4 rounded-xl bg-surfaceSecondary/70 border border-borderSubtle space-y-1.5">
            <div className="flex items-center justify-between text-[11px] font-mono text-textSecondary">
              <span className="flex items-center gap-1.5">
                <FileWarning className="w-3.5 h-3.5 text-warningYellow" /> Flagged Signals
              </span>
              <span className="font-bold text-warningYellow">
                {threatIndicators.length + hallmarks.length}
              </span>
            </div>
            <div className="flex items-center gap-2 mt-2">
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-red-500/20 text-red-300">
                {threatIndicators.length} Threats
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-purpleAccent/20 text-purpleAccent">
                {hallmarks.length} Hallmarks
              </span>
            </div>
            <div className="text-[10px] text-textSecondary leading-tight">
              Evaluated against 50+ synthetic & threat rules
            </div>
          </div>
        </div>
      </Card>

      {/* 4. Interactive Sentence-by-Sentence Forensic Heatmap */}
      <Card className="p-6 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-borderSubtle">
          <div className="flex items-center gap-2">
            <Search className="w-4 h-4 text-purpleAccent" />
            <h4 className="text-xs font-bold font-mono uppercase tracking-wider text-textPrimary">
              Sentence-by-Sentence Dual-Matrix Heatmap
            </h4>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-[11px] font-mono text-textSecondary">Filter:</span>
            <div className="flex rounded-lg bg-surfaceSecondary p-0.5 border border-borderSubtle text-[10px] font-mono">
              <button
                onClick={() => setFilterLevel('ALL')}
                className={`px-2 py-0.5 rounded ${
                  filterLevel === 'ALL' ? 'bg-purpleAccent text-white' : 'text-textSecondary hover:text-white'
                }`}
              >
                All ({perSentenceAnalysis.length})
              </button>
              <button
                onClick={() => setFilterLevel('DECEPTIVE_ONLY')}
                className={`px-2 py-0.5 rounded ${
                  filterLevel === 'DECEPTIVE_ONLY' ? 'bg-red-500 text-white' : 'text-textSecondary hover:text-white'
                }`}
              >
                Deceptive ({perSentenceAnalysis.filter((s) => s.isDeceptive).length})
              </button>
              <button
                onClick={() => setFilterLevel('AI_ONLY')}
                className={`px-2 py-0.5 rounded ${
                  filterLevel === 'AI_ONLY' ? 'bg-purpleAccent text-white' : 'text-textSecondary hover:text-white'
                }`}
              >
                High AI
              </button>
              <button
                onClick={() => setFilterLevel('HUMAN_ONLY')}
                className={`px-2 py-0.5 rounded ${
                  filterLevel === 'HUMAN_ONLY' ? 'bg-emerald-500 text-white' : 'text-textSecondary hover:text-white'
                }`}
              >
                Human
              </button>
            </div>
          </div>
        </div>

        {/* Legend */}
        <div className="flex flex-wrap items-center gap-4 text-[11px] font-mono text-textSecondary pb-2">
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-purple-500/30 border border-purple-500" />
            <span>High AI Origin (&ge; 70%)</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-red-500/30 border border-red-500" />
            <span>Deceptive Phishing Cue</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded bg-emerald-500/20 border border-emerald-500/40" />
            <span>Organic / Benign</span>
          </div>
          <span className="text-textSecondary/60 italic ml-auto">
            (Click any sentence to inspect detailed forensic rationale)
          </span>
        </div>

        {/* Heatmap Canvas */}
        <div className="p-4 rounded-2xl bg-darkBg/60 border border-borderSubtle leading-relaxed font-sans text-xs space-y-2 max-h-[350px] overflow-y-auto">
          {filteredSentences.length === 0 ? (
            <p className="text-textSecondary italic">No sentences match the selected filter.</p>
          ) : (
            <div className="flex flex-wrap gap-1.5">
              {filteredSentences.map((item) => {
                const isSelected = selectedSentenceIndex === item.index;
                const isItemHighAi = item.aiProbability >= 70;
                const isDeceptive = Boolean(item.isDeceptive);

                return (
                  <span
                    key={item.index}
                    onClick={() => setSelectedSentenceIndex(item.index)}
                    className={`cursor-pointer px-2 py-1 rounded-lg transition-all border ${
                      isSelected
                        ? 'ring-2 ring-purpleAccent scale-[1.01] shadow-lg'
                        : ''
                    } ${
                      isDeceptive
                        ? 'bg-red-500/20 border-red-500/50 text-red-200 hover:bg-red-500/30'
                        : isItemHighAi
                        ? 'bg-purpleAccent/15 border-purpleAccent/30 text-purple-200 hover:bg-purpleAccent/25'
                        : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-200 hover:bg-emerald-500/20'
                    }`}
                  >
                    {isDeceptive && (
                      <span className="mr-1 text-[10px] font-mono text-red-400 font-bold">[!]</span>
                    )}
                    {item.sentence}
                    <span className="ml-1.5 text-[9px] font-mono opacity-60 font-bold">
                      [{item.aiProbability}% AI]
                    </span>
                  </span>
                );
              })}
            </div>
          )}
        </div>

        {/* Sentence Inspector Detail Drawer */}
        {selectedSentence && (
          <div className="p-4 rounded-xl bg-purpleAccent/10 border border-purpleAccent/30 space-y-2 animate-fadeIn text-xs">
            <div className="flex items-center justify-between border-b border-purpleAccent/20 pb-2">
              <div className="flex items-center gap-2">
                <Sparkles className="w-3.5 h-3.5 text-purpleAccent" />
                <strong className="font-mono text-textPrimary">
                  Sentence #{selectedSentence.index + 1} Dual-Matrix Analysis
                </strong>
                <span
                  className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold ${
                    selectedSentence.aiProbability >= 70
                      ? 'bg-purpleAccent/20 text-purpleAccent'
                      : 'bg-emerald-500/20 text-emerald-300'
                  }`}
                >
                  {selectedSentence.aiProbability}% AI
                </span>
                {selectedSentence.isDeceptive && (
                  <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-red-500/20 text-red-400 border border-red-500/30">
                    DECEPTIVE CUE
                  </span>
                )}
              </div>
              <button
                onClick={() => setSelectedSentenceIndex(null)}
                className="text-textSecondary hover:text-white text-[11px] font-mono"
              >
                Close ×
              </button>
            </div>
            <p className="text-textPrimary italic font-sans">
              "{selectedSentence.sentence}"
            </p>
            {selectedSentence.reason && (
              <p className="text-textSecondary text-[11px]">
                <strong>Forensic Rationale:</strong> {selectedSentence.reason}
              </p>
            )}
            {selectedSentence.deceptiveIndicators?.length > 0 && (
              <div className="flex items-center gap-1.5 pt-1">
                <span className="text-[10px] text-red-400 font-mono font-bold">Threat Cues:</span>
                {selectedSentence.deceptiveIndicators.map((di, i) => (
                  <span
                    key={i}
                    className="text-[10px] font-mono px-2 py-0.5 rounded bg-red-500/20 text-red-300 border border-red-500/30"
                  >
                    {di}
                  </span>
                ))}
              </div>
            )}
            {selectedSentence.hallmarksFound?.length > 0 && (
              <div className="flex items-center gap-1.5 pt-1">
                <span className="text-[10px] text-textSecondary font-mono">LLM Hallmarks:</span>
                {selectedSentence.hallmarksFound.map((hf, i) => (
                  <span
                    key={i}
                    className="text-[10px] font-mono px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30"
                  >
                    "{hf}"
                  </span>
                ))}
              </div>
            )}
          </div>
        )}
      </Card>

      {/* 5. Detected Threats & Hallmarks Side-by-Side */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Threat & Deception Indicators Card */}
        <Card className="p-6 space-y-3">
          <div className="flex items-center justify-between pb-2 border-b border-borderSubtle">
            <div className="flex items-center gap-2">
              <ShieldAlert className="w-4 h-4 text-red-400" />
              <h4 className="text-xs font-bold font-mono uppercase tracking-wider text-textPrimary">
                Threat & Deception Indicators ({threatIndicators.length})
              </h4>
            </div>
            <span
              className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${
                isHarmful ? 'bg-red-500/20 text-red-400' : 'bg-emerald-500/20 text-emerald-400'
              }`}
            >
              {threatVerdict.replace(/_/g, ' ')}
            </span>
          </div>

          {threatIndicators.length === 0 ? (
            <div className="py-6 text-center space-y-1">
              <CheckCircle2 className="w-6 h-6 text-emerald-400 mx-auto" />
              <p className="text-xs text-emerald-400 font-mono font-bold">
                Zero Deceptive or Threat Indicators Flagged
              </p>
              <p className="text-[11px] text-textSecondary">
                No credential harvesting, urgent account suspension, or wire scam patterns observed.
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {threatIndicators.map((ti, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-surfaceSecondary border border-red-500/20 text-xs space-y-1.5"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-red-400 font-bold flex items-center gap-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-red-400" />
                      {ti.indicator || ti.category}
                    </span>
                    <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-red-500/20 text-red-300 font-bold uppercase">
                      {ti.severity || 'HIGH'}
                    </span>
                  </div>
                  {ti.evidence && (
                    <div className="text-[11px] font-mono text-textPrimary bg-darkBg/60 px-2 py-1 rounded border border-white/5">
                      "{ti.evidence}"
                    </div>
                  )}
                  <p className="text-[11px] text-textSecondary leading-relaxed">{ti.explanation}</p>
                </div>
              ))}
            </div>
          )}
        </Card>

        {/* LLM Signature Hallmarks Card */}
        <Card className="p-6 space-y-3">
          <div className="flex items-center justify-between pb-2 border-b border-borderSubtle">
            <div className="flex items-center gap-2">
              <Bot className="w-4 h-4 text-purpleAccent" />
              <h4 className="text-xs font-bold font-mono uppercase tracking-wider text-textPrimary">
                LLM Signature Hallmarks ({hallmarks.length})
              </h4>
            </div>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-purpleAccent/20 text-purpleAccent font-bold">
              {authorshipVerdict.replace(/_/g, ' ')}
            </span>
          </div>

          {hallmarks.length === 0 ? (
            <div className="py-6 text-center space-y-1">
              <UserCheck className="w-6 h-6 text-emerald-400 mx-auto" />
              <p className="text-xs text-emerald-400 font-mono font-bold">
                Zero Classic LLM Clichés Detected
              </p>
              <p className="text-[11px] text-textSecondary">
                Text lacks mechanical conversational formulas and robotic boilerplate.
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {hallmarks.map((h, idx) => (
                <div
                  key={idx}
                  className="p-3 rounded-xl bg-surfaceSecondary border border-borderSubtle text-xs space-y-1"
                >
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-warningYellow font-bold">
                      "{h.matched}"
                    </span>
                    <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 text-textSecondary">
                      {h.category}
                    </span>
                  </div>
                  <p className="text-[11px] text-textSecondary">{h.description}</p>
                </div>
              ))}
            </div>
          )}
        </Card>
      </div>

      {/* 6. Security Analyst Action Card */}
      <Card className="p-6 space-y-3">
        <div className="flex items-center gap-2 pb-2 border-b border-borderSubtle">
          <CheckCircle2 className="w-4 h-4 text-cyanAccent" />
          <h4 className="text-xs font-bold font-mono uppercase tracking-wider text-textPrimary">
            Analyst Actionable Recommendations
          </h4>
        </div>

        <div className="p-3.5 rounded-xl bg-surfaceSecondary border border-borderSubtle text-xs text-textPrimary leading-relaxed space-y-2">
          <div>
            <strong className="text-cyanAccent font-mono">Recommended Next Steps:</strong>
            <p className="text-textSecondary mt-1">
              {suggestedAnalystAction ||
                (isHarmful
                  ? 'Isolate recipient workstation and block outbound connections to referenced domains. Do NOT submit credentials.'
                  : isHighAi
                  ? 'Evaluate business context. While text is AI-generated, no threat vectors were detected.'
                  : 'Email displays authentic human composition and zero threat patterns.')}
            </p>
          </div>
        </div>

        {linguisticIndicators?.length > 0 && (
          <div className="space-y-2 pt-2">
            <div className="text-[10px] font-mono uppercase tracking-wider text-textSecondary">
              Observed Stylistic Markers
            </div>
            <ul className="space-y-1.5 text-xs text-textSecondary">
              {linguisticIndicators.map((ind, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-primaryBlue">•</span>
                  <span>
                    <strong className="text-textPrimary">{ind.indicator}:</strong>{' '}
                    {ind.explanation}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </Card>
    </div>
  );
}
